# Generated by Django 3.1.7 on 2021-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210316_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='You should specify a title', max_length=200, verbose_name='Title'),
        ),
    ]
